### ISSUE TITLE
RuntimeError when loading mode.

### ISSUE THREAD

**Issue by zebin-huang** [TheRoboticsClub/gsoc2023-Meiqi_Zhao#3]
Hi, I just encountered a RuntimeError due to a size mismatch when following the documentation to run test.ipynb with [models/v10.0.pth](https://github.com/TheRoboticsClub/gsoc2023-Meiqi_Zhao/tree/main/src/ModifiedDeepestLSTMTinyPilotNet/models).

Could there be a version mismatch or an update in the model architecture that is causing this issue?

**Error Message**
> RuntimeError: Error(s) in loading state_dict for PilotNetOneHot:
>   size mismatch for fc_3.weight: copying a param with shape torch.Size([2, 10]) from checkpoint, the shape in current model is torch.Size([3, 10]).
>   size mismatch for fc_3.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).

  

**Code Snippet**
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = PilotNetOneHot((288, 200, 6), 3, 4, 4)
model.load_state_dict(torch.load("./models/segmentation-based-imitation-learning-in-CARLA/v10.0.pth"))
model = model.to(device)
model.eval()
```

**Comment by sergiopaniego** [comment]
If you look at the training script (https://github.com/TheRoboticsClub/gsoc2023-Meiqi_Zhao/blob/main/src/ModifiedDeepestLSTMTinyPilotNet/train.ipynb), the output of the model can be combined or not. 

The output is throttle, steer, and brake. 
If the case of `combined=True,` the output is `throttle-brake + steer`. 
If the `combined=False`, the output is` throttle, steer and brake`.

The checkpoint that you're using was trained with `combined=True` so you have to consider that when creating the instance. Review these 2 notebooks and the model architecture file  :smile:
